### ISSUE TITLE
Needs function to download alternate subs if first file is no good

### ISSUE THREAD

**Issue by Rabcor** [davidde/mpv-autosub#14] opened 2020-11-22 15:31 UTC
Sometimes this script will download subs that are bad, for instance I have this movie, white snake, and the downloaded sub for it is 
_White.Snake.2019.1080p.BluRay.x264.AAC5.1-[YTS.LT].en.srt_

It's (entire) content:

```
`1
00:00:30,000 --> 00:00:36,000
Provided by YTS.LT

2
00:00:36,500 --> 00:00:42,000
Find the official YIFY movies site at
https://YTS.LT

3
00:30:30,000 --> 00:30:36,000
Downloaded from YTS.LT

4
01:00:30,000 --> 01:00:36,000
Download more movies for free
from YTS.LT
`
```

Nevermind being a mistimed subtitle file, it's just not a real subtitle at all.

I'd like to have the ability to press a key that makes it look for an alternative subtitle file instead of the one it first downloaded.

Additionally or perhaps alternatively(?) an automated feature that checks if the filesize of the subtitle file is at least over 1kb and rejects the file if it isn't to prevent this specific scenario might be nice.

**Comment by davidde** [comment] 2020-11-22 23:29
Duplicate of #9 

This request belongs here: https://github.com/Diaoul/subliminal/issues/new
Also, subtitle files like that should be flagged and removed on the provider's end.

**Comment by davidde** [comment] 2020-11-22 23:35
Request belongs here: https://github.com/Diaoul/subliminal/issues/new

Also, subtitle files like that should be flagged and removed on the provider's end.

**Comment by Rabcor** [comment] 2020-11-23 01:44
> Request belongs here: https://github.com/Diaoul/subliminal/issues/new
> 
> Also, subtitle files like that should be flagged and removed on the provider's end.

In a perfect world; of course the provider would handle that ;)

Sorry for the duplicate.

**Comment by davidde** [comment] 2020-11-23 22:18
No worries.

Wish I _could_ fix this on my end.

**Closed by davidde** 2020-11-23 22:18 UTC
